acl_policy_path: ""
cli:
  insecure: false
  timeout: 5s
db_path: /tmp/integration_test_db.sqlite3
db_ssl: false
db_type: sqlite3
relay:
  auto_update_enabled: false
  server:
    enabled: false
    stun:
      enabled: true
  update_frequency: 1m
  urls:
    - https://resources.optm.com/relay-dev.json
dns_config:
  override_local_dns: true
  base_domain: ninjapanda.net
  domains: []
  magic_dns: true
  nameservers:
    - 1.1.1.1
ephemeral_node_inactivity_timeout: 30m
node_update_check_interval: 30s
grpc_allow_insecure: false
grpc_listen_addr: :50443
ip_prefixes:
  - fd7a:115c:a1e0::/48
  - 100.64.0.0/10
listen_addr: 0.0.0.0:18080
kafka:
  update_interval: 60s
log:
  level: trace
  format: text
ztmlog:
  enabled: false
metrics_listen_addr: 127.0.0.1:19090
oidc:
  only_start_if_oidc_is_available: true
  scope:
    - openid
    - profile
    - email
  strip_email_domain: true
private_key_path: private.key
noise:
  private_key_path: noise_private.key
server_url: http://ninjapanda:18080
tls_letsencrypt_cache_dir: /var/www/.cache
tls_letsencrypt_challenge_type: HTTP-01
unix_socket: /var/run/ninjapanda.sock
unix_socket_permission: "0o770"
randomize_client_port: false
